#pragma once
#include "vex.h"
#include "drivetrain.h"
#include "intakes.h"
#include "autonMethodLibrary.h"

void leftAndCenter(void);
void Right(void);
void Left(void);
void leftAndMiddle(void);
void rightAndMiddle(void);
void progSkills(void);
void homeRow(void);
void homeRowRight(void);
void rightAndSide(void);
void Side(void);
void Center(void);
void OrcahBlue(void);
void OrcahRed(void);